# To be tuned
SafetyPendulum-v1:
  # callback:
  #   - rl_zoo3.callbacks.ParallelTrainCallback
  n_timesteps: 200000
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-3


CarRacing-v3:
  env_wrapper:
    - rl_zoo3.wrappers.FrameSkip:
        skip: 2
    # wrapper from https://github.com/araffin/aae-train-donkeycar
    - ae.wrapper.AutoencoderWrapper:
        ae_path: "logs/car_racing_rgb_160.pkl"
    - rl_zoo3.wrappers.HistoryWrapper:
        horizon: 2
  # frame_stack: 4
  normalize: True
  n_envs: 2
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 300000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.02
  train_freq: 8
  gradient_steps: 10
  learning_starts: 1000
  use_sde: True
  use_sde_at_warmup: True
