"""Standalone 4-state reduced-dynamics kernel for the vault balance robot.

This is the ONLY robot-specific dynamics shared with this package: the closed-form
reduced equations of motion over x = [v, theta, theta_dot, psi_dot], generated by
symbolic projection of the full model and CSE-compiled to a single C function
(`csrc/reduced_opt6.c`, geometry baked in at codegen). It does NOT pull in the
framework / hybrid simulator or the deployed controller — just `f` and the analytic
Jacobians, which is everything the HJ reach-avoid solve, the RL env, and the iLQR need.

`CoupledOpt6().f(x, u)`           -> xd = [v_dot, theta_dot, theta_ddot, psi_ddot]
`CoupledOpt6().jacobians(x, u)`   -> (fx 4x4, fu 4x2)   continuous-time analytic Jacobians

Requires: numpy + a C compiler (cc/gcc) on PATH. The kernel is compiled once to a
temp .so and cached. Pure NumPy/ctypes otherwise.
"""
import ctypes
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

_SRC = Path(__file__).resolve().parent / "csrc" / "reduced_opt6.c"
_lib = None  # cached ctypes handle

# Geometry baked into the kernel at codegen (metadata; the kernel itself carries it).
OPT6_R = 0.12705     # v2 body-wheel radius (m)
OPT6_DH = 0.140375   # v2 half wheel-separation (m)


def _load():
    """Compile (once) and load the reduced-dynamics kernel. Cached."""
    global _lib
    if _lib is not None:
        return _lib
    cc = shutil.which("cc") or shutil.which("gcc")
    if cc is None:
        raise RuntimeError("need a C compiler (cc/gcc) on PATH to build the reduced-dynamics kernel")
    so = Path(tempfile.gettempdir()) / "libvault_reduced_opt6.so"
    if (not so.exists()) or so.stat().st_mtime < _SRC.stat().st_mtime:
        subprocess.run([cc, "-O2", "-fPIC", "-shared", "-o", str(so), str(_SRC), "-lm"],
                       check=True, capture_output=True)
    lib = ctypes.CDLL(str(so))
    lib.reduced_struct_fjac_f32.argtypes = [ctypes.POINTER(ctypes.c_float)] * 5
    lib.reduced_struct_fjac_f32.restype = None
    _lib = lib
    return lib


class CoupledOpt6:
    """Closed-form reduced 4-state dynamics (opt6 kernel), f + analytic Jacobians.

    State x = [v, theta, theta_dot, psi_dot]; control u = [tau_L, tau_R] (N*m, left/right wheel).
    Continuous-time: xd = [v_dot, theta_dot, theta_ddot, psi_ddot].
    """

    def __init__(self):
        self._lib = _load()
        self.r = OPT6_R
        self.d = OPT6_DH

    def _fjac(self, x, u_LR):
        xf = np.ascontiguousarray(x, dtype=np.float32)
        # the kernel's control order is [tau_R, tau_L]; we expose [tau_L, tau_R] -> swap.
        uf = np.array([u_LR[1], u_LR[0]], dtype=np.float32)
        xd = np.zeros(4, dtype=np.float32)
        fx = np.zeros(16, dtype=np.float32)
        fu = np.zeros(8, dtype=np.float32)
        self._lib.reduced_struct_fjac_f32(
            xf.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            uf.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            xd.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            fx.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            fu.ctypes.data_as(ctypes.POINTER(ctypes.c_float)))
        fx_m = fx.reshape(4, 4, order="F").astype(np.float64)         # Julia build_function: column-major
        fu_m = fu.reshape(4, 2, order="F").astype(np.float64)[:, ::-1].copy()  # swap cols back -> [tau_L, tau_R]
        return xd.astype(np.float64), fx_m, fu_m

    def f(self, x, u):
        xd, _, _ = self._fjac(x, u)
        return xd

    def jacobians(self, x, u):
        _, fx, fu = self._fjac(x, u)
        return fx, fu


if __name__ == "__main__":
    m = CoupledOpt6()
    x = np.array([0.3, 0.1, -0.2, 0.4]); u = np.array([1.0, -0.5])
    xd = m.f(x, u); fx, fu = m.jacobians(x, u)
    print("xd =", np.round(xd, 4))
    print("fx =\n", np.round(fx, 3))
    print("fu =\n", np.round(fu, 3))
