"""Standalone 4-state reduced-dynamics kernel for the vault balance robot.

This is the ONLY robot-specific dynamics shared with this package: the closed-form
reduced equations of motion over x = [v, theta, theta_dot, psi_dot], generated by
symbolic projection of the full model and CSE-compiled to a single C function in
the provenance-pinned vault-controller model release. It does NOT pull in the
framework / hybrid simulator or the deployed controller -- just `f` and the
analytic Jacobians, which is everything the HJ reach-avoid solve, the RL env,
and the iLQR need.

`CoupledOpt6().f(x, u)`           -> xd = [v_dot, theta_dot, theta_ddot, psi_ddot]
`CoupledOpt6().jacobians(x, u)`   -> (fx 4x4, fu 4x2)   continuous-time analytic Jacobians

Requires: numpy + a C compiler (cc/gcc) on PATH. The kernel is compiled once to a
temp .so and cached. Pure NumPy/ctypes otherwise.
"""
import ctypes
import os
import shutil
import subprocess
import tempfile
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np

from .model_release import get_model_release

_lib = None  # cached ctypes handle


@lru_cache(maxsize=1)
def _release_inputs() -> tuple[Any, Path, dict[str, Any]]:
    release = get_model_release()
    return (
        release,
        release.artifact_path("opt6_kernel"),
        release.load_json("composite_params"),
    )


def __getattr__(name: str) -> Any:
    if name == "_SRC":
        return _release_inputs()[1]
    if name == "OPT6_R":
        return _release_inputs()[2]["wheel_radius"]
    if name == "OPT6_DH":
        return _release_inputs()[2]["wheel_sep"] / 2.0
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | {"_SRC", "OPT6_R", "OPT6_DH"})


def _load():
    """Compile (once) and load the reduced-dynamics kernel. Cached."""
    global _lib
    if _lib is not None:
        return _lib
    cc = shutil.which("cc") or shutil.which("gcc")
    if cc is None:
        raise RuntimeError("need a C compiler (cc/gcc) on PATH to build the reduced-dynamics kernel")
    release, source, _ = _release_inputs()
    source_hash = release.model_hashes["opt6_kernel_sha256"][:16]
    so_path = Path(tempfile.gettempdir()) / f"libvault_reduced_opt6_{source_hash}.so"
    if not so_path.exists():
        temporary = so_path.with_name(f"{so_path.name}.{os.getpid()}.tmp")
        try:
            subprocess.run(
                [
                    cc,
                    "-O2",
                    "-fPIC",
                    "-shared",
                    "-o",
                    str(temporary),
                    str(source),
                    "-lm",
                ],
                check=True,
                capture_output=True,
            )
            os.replace(temporary, so_path)
        finally:
            temporary.unlink(missing_ok=True)
    lib = ctypes.CDLL(str(so_path))
    lib.reduced_struct_fjac_f32.argtypes = [ctypes.POINTER(ctypes.c_float)] * 5
    lib.reduced_struct_fjac_f32.restype = None
    _lib = lib
    return lib


class CoupledOpt6:
    """Closed-form reduced 4-state dynamics (opt6 kernel), f + analytic Jacobians.

    State x = [v, theta, theta_dot, psi_dot]; control u = [tau_L, tau_R] (N*m, left/right wheel).
    Continuous-time: xd = [v_dot, theta_dot, theta_ddot, psi_ddot].
    """

    def __init__(self):
        self._lib = _load()
        _, _, params = _release_inputs()
        self.r = params["wheel_radius"]
        self.d = params["wheel_sep"] / 2.0

    def _fjac(self, x, u_LR):
        xf = np.ascontiguousarray(x, dtype=np.float32)
        # the kernel's control order is [tau_R, tau_L]; we expose [tau_L, tau_R] -> swap.
        uf = np.array([u_LR[1], u_LR[0]], dtype=np.float32)
        xd = np.zeros(4, dtype=np.float32)
        fx = np.zeros(16, dtype=np.float32)
        fu = np.zeros(8, dtype=np.float32)
        self._lib.reduced_struct_fjac_f32(
            xf.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            uf.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            xd.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            fx.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
            fu.ctypes.data_as(ctypes.POINTER(ctypes.c_float)))
        fx_m = fx.reshape(4, 4, order="F").astype(np.float64)         # Julia build_function: column-major
        fu_m = fu.reshape(4, 2, order="F").astype(np.float64)[:, ::-1].copy()  # swap cols back -> [tau_L, tau_R]
        return xd.astype(np.float64), fx_m, fu_m

    def f(self, x, u):
        xd, _, _ = self._fjac(x, u)
        return xd

    def jacobians(self, x, u):
        _, fx, fu = self._fjac(x, u)
        return fx, fu


if __name__ == "__main__":
    m = CoupledOpt6()
    x = np.array([0.3, 0.1, -0.2, 0.4]); u = np.array([1.0, -0.5])
    xd = m.f(x, u); fx, fu = m.jacobians(x, u)
    print("xd =", np.round(xd, 4))
    print("fx =\n", np.round(fx, 3))
    print("fu =\n", np.round(fu, 3))
